name: news-tenant
additional_hostnames:
  - alpha.news-tenant
  - beta.news-tenant
  - gamma.news-tenant
  - delta.news-tenant
  - omega.news-tenant
  - sigma.news-tenant
type: laravel
docroot: public
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_fqdns: []
database:
  type: mysql
  version: "8.0"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false
default_container_timeout: "240"
